name: "{{name}}"
description: "{{name}} feature for Zephyr app"
publish_to: "none"
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.2.0
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^8.2.0
  injectable: ^2.5.2
  freezed_annotation: ^3.0.0

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.0
  mocktail: ^1.0.0
  injectable_generator: ^2.6.2
