name: "{{name}}"
description: "{{name}} feature for Zephyr app"
publish_to: "none"
resolution: workspace

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  auto_route: ^10.2.2
  equatable: ^2.0.7
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  injectable: ^2.6.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  mocktail: ^1.0.4
  injectable_generator: ^2.9.1
